<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' :: ');
$this->headTitle('Zend Framework');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php // echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/site.css'); ?>
        
        <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/site.js');?>
    </head>
    <body>
        <div id="content">
            <h1><?php echo $this->escape($this->title); ?></h1>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>